
from setuptools import setup, find_packages

setup(
    name="nadesiko3-python",
    version="2.0.0",
    description="Nadesiko3 Compatible Japanese Programming Language Module",
    author="Nadesiko Compatible Module",
    author_email="nadesiko@example.com",
    url="https://github.com/nadesiko3-python/nadesiko3-python",
    packages=find_packages(where="src"),
    install_requires=[
        "requests>=2.25.0",
        "Pillow>=8.0.0",
        "opencv-python>=4.5.0",
        "pandas>=1.3.0",
        "scikit-learn>=1.0.0",
        "matplotlib>=3.3.0",
        "numpy>=1.20.0",
        "pyautogui>=0.9.0",
        "pyperclip>=1.8.0",
        "pygame>=2.0.0",
        "qrcode>=6.1.0",
        "python-barcode>=0.15.0",
        "cryptography>=3.4.0",
        "pyyaml>=5.4.0",
        "openpyxl>=3.0.0",
    ],
    python_requires=">=3.6",
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Education",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Topic :: Education",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "Topic :: Programming Languages :: Python",
    ],
    keywords="nadesiko3 japanese programming education beginner",
    project_urls={
        "Bug Reports": "https://github.com/nadesiko3-python/nadesiko3-python/issues",
        "Source": "https://github.com/nadesiko3-python/nadesiko3-python",
        "Documentation": "https://github.com/nadesiko3-python/nadesiko3-python/blob/main/README.md",
    },
)
